### ISSUE TITLE
上海嘉定区

### ISSUE THREAD

**Issue by mxwgg** [mumuy/data_location#10]
上海嘉定区缺少“嘉定工业区”。从官方的网站上可以看到，嘉定区下辖3街道7镇1新区1市级工业区。
参考网址：http://www.jiading.gov.cn/jzpd ，左下角有相应的位置

**Comment by mumuy** [comment]
认真看数据说明，嘉定工业区属于行政管理区并非行政区！嘉定工业区由嘉定工业区管委会实行管理，并未挂牌“xx区人民政府”

**Comment by mxwgg** [comment]
行政管理区也好，行政区也好，现实情况是，少了嘉定工业区，行政区域内属于嘉定工业区的这一部分土地面积是无法选择的，因为它不属于其他的镇、街道，只归嘉定工业区管。嘉定工业区相当于跟“镇、街道”同级。既然叫“中国行政区划信息”，嘉定工业区是不能忽略的。
另一个参考网址：http://www.jiading.gov.cn/qqpd/zjjd/jzqh

**Comment by mumuy** [comment]
嘉定工业区归嘉定区人民政府管啊！
行政管理区和行政区不同的概念啊，你给的参考地址并没有参考价值～
你可以去上海市嘉定区人民政府官网看:http://jiading.gov.cn/infopublicity/department/show/33
嘉定工业区管委会是嘉定区人民政府的派出机关，受区人民政府领导，依据法律、法规的规定，在本辖区内行使相应的政府管理职能。

**Comment by mumuy** [comment]
或者可以在百科中查找上海市辖区，一共16个辖区，并未包含“嘉定工业区”，因为“嘉定工业区”是嘉定区下面的

**Comment by mxwgg** [comment]
就是因为嘉定区下辖的镇、街道中，没有嘉定工业区，我才有疑问的

**Comment by mumuy** [comment]
哦哦，这种状态是部分放权的，日常管理可以由管理委员会直接管理。而且行政管理区在一定时候是可能成为行政区的，但需要有国务院公告批复。
比如深圳前段时间就有“华龙新区”“坪山新区”升级为行政区

**Comment by mxwgg** [comment]
你收集的这个数据库中，其他地区的情况我不知道，对于嘉定我是很了解的。如果像嘉定工业区这种都不列入，那我是不敢用这个数据库的，因为信息真的不全。估计其他地方也会有这种情况吧。阿里的地址库里面，都有嘉定工业区的，隶属于嘉定区。京东之前也有“嘉定工业区”的，后来京东合并为“城区”了

**Comment by mumuy** [comment]
行政区和行政管理区是两种概念，在分类学中如果你按照两个标准去分类的话，可能会造成一种情况：我到底是要选择嘉定区还是嘉定工业区？因为你按两个分类标准去划分东西了！
不需要看阿里还是京东，每个人都有自己做事的原则吧，你不敢用我也不能强求不是吗？
我这个数据库做的是行政区划，我就只做行政区划，如果把其他的放进来我相信更多人会疯的……

**Comment by mxwgg** [comment]
可是我要选择是嘉定区下辖的嘉定工业区...

**Comment by mumuy** [comment]
那也不行啊！下面一级是镇或街道……需要看是否有“镇政府”或“街道办事处”

加入的话就相当于学校管理按专业班级分类，你非要再加入学生社团一样

**Comment by mumuy** [comment]
除非是有行政区划代码，如果有的话也只是放在第四级里面……而不是在list.json里面。目前我得到的数据看，菊园新区管委会是属于第四级的，也就是镇或街道同级

**Comment by mxwgg** [comment]
跟菊园新区管委会同级的。一开始我就说了，上海嘉定区缺少“嘉定工业区”，嘉定区下辖3街道7镇1新区1市级工业区，3街道7镇1新区都有，市级工业区（就是嘉定工业区）没有

**Comment by mumuy** [comment]
嘉定工业区并没有找到行政区划代码，而且菊园新区管委会是在第四级，三级联动插件里面不能显示

**Comment by mumuy** [comment]
嘉定工业区是嘉定区的派出单位，嘉定区属于三级的，那它肯定不是三级了……
嘉定工业区下面管理几个镇，镇是四级的，那它肯定不是四级了……
你觉得该归哪里呢？管理会是区政府的派出单位，并非下级行政区

**Comment by mumuy** [comment]
不能光从名字相近来看是否同级的，是否为行政单位国务院都有专门的管理办法，修改需要文件批复才算……
这里是2015年9月份的嘉定区下属行政单位：
http://www.stats.gov.cn/tjsj/tjbz/tjyqhdmhcxhfdm/2015/31/01/310114.html
