### ISSUE TITLE
town 下缺少不设区的地级市直辖乡镇街道，如广东东莞虎门

### ISSUE THREAD

**Issue by larryli** [mumuy/data_location#11]
缺少：
- [town/441900.json](https://github.com/mumuy/data_location/blob/gh-pages/town/441900.json) 东莞市
- [town/442000.json](https://github.com/mumuy/data_location/blob/gh-pages/town/442000.json) 中山市
- [town/460400.json](https://github.com/mumuy/data_location/blob/gh-pages/town/460400.json) 儋州市

另外，620200 嘉峪关市存在下级数据：
- [town/620201.json](https://github.com/mumuy/data_location/blob/gh-pages/town/620201.json)
但在 [list.json](https://github.com/mumuy/data_location/blob/gh-pages/list.json) 没有数据。
而且此数据只有 3 镇，没有 7 街道数据（嘉峪关市下辖7街道、3镇：胜利街道、五一街道、新华街道、建设街道、前进街道、峪苑街道、朝阳街道、峪泉镇、新城镇、文殊镇）。
建议直接更名为 [town/620200.json](https://github.com/mumuy/data_location/blob/gh-pages/town/620200.json) 并增补数据。

参考：[不设区的市](https://zh.wikipedia.org/wiki/%E4%B8%8D%E8%AE%BE%E5%8C%BA%E7%9A%84%E5%B8%82)、[嘉峪关市行政区划](https://zh.wikipedia.org/wiki/%E5%98%89%E5%B3%AA%E5%85%B3%E5%B8%82#.E8.A1.8C.E6.94.BF.E5.8C.BA.E5.88.92)

**Comment by mumuy** [comment]
谢谢提示，东莞市行政区划比较特别，没有第三级别……写爬虫爬取的时候没有抓到

**Comment by mumuy** [comment]
第四级数据并不是实时更新的，国务院官网没更新，有一定延时
