### ISSUE TITLE
要是有第五级数据就更帅了

### ISSUE THREAD

**Issue by ganfang** [mumuy/data_location#16]
多个项目正在使用你的插件，很不错。不过有需要第五级数据。这里有就最棒了。第一次使用github并评论。

**Comment by mumuy** [comment]
五级？国家的编码里面好像没有吧

**Comment by zhanzheng100** [comment]
牛，写了这么多

**Comment by ganfang** [comment]
@mumuy ,有的，省、市、县、乡镇、村。第五级的12位编码，你的插件代码结构好，在你的基础上扩到第五级，就是不知道怎么抓数据：http://www.stats.gov.cn/tjsj/tjbz/tjyqhdmhcxhfdm/2016/index.html

**Comment by mumuy** [comment]
nodejs  抓的，因为日常就用3级，这个四级都是扩展出来的，举个例子而已

**Comment by ganfang** [comment]
@mumuy 嗯，一般三级就够了，谢谢分享。有项目需要五级就仿你的代码扩到了第五级，但是不会nodejs，不会爬虫。要抓第五级数据很蛋疼。
