### ISSUE TITLE
330112对应的town文件没有

### ISSUE THREAD

**Issue by aotian16** [mumuy/data_location#25]
貌似对应着330185去了。

是不是临安市改为临安区后没有修改相应的down文件呢?

**Comment by mumuy** [comment]
第4级数据没有一直更新，更新频率不那么频繁

**Comment by ray534** [comment]
如果不更新 我们这边做 联动地址 会一直报404错误 对开发有影响

**Comment by mumuy** [comment]
> 如果不更新 我们这边做 联动地址 会一直报404错误 对开发有影响

你可以做兼容处理，本身就是开源项目，没有保证一直实时更新的
