### ISSUE TITLE
哥们,有没有区委会这一级别的数据

### ISSUE THREAD

**Issue by ChengZi1024** [mumuy/data_location#27]
我们项目对行政区划细粒度较高,需要网格化处理,但是您提供的数据只有街道办这一级别,那能不能提供一下区委会级别啊?

**Comment by mumuy** [comment]
那叫居委会，居委会并不是行政机构，而是基层群众性自治组织，和农村的村委会差不多。这部分数据不在项目的考虑范围，不提供
