### ISSUE TITLE
请问行政区域编码判断规则是什么

### ISSUE THREAD

**Issue by shawndongyangyang** [mumuy/data_location#28]
如果我要分级，省是一级，市是二级，区、县是三级，请问算法规则什么
我自己摸索出来的是：
行政编码最后4位都为0000的就是省
行政编码除以100为0的就是市
其他的为区、县
但是！！！按这个规则处理完了之后我感觉很多归类都与真实的行政规划不符合，
请问这个具体算法是什么，如何才能根据行政编码做一级二级分类，

**Comment by mumuy** [comment]
结尾90xx为省直管的县

算法看源代码吧

**Comment by shawndongyangyang** [comment]
@mumuy 源代码在哪？

**Comment by mumuy** [comment]
https://github.com/mumuy/widget/blob/master/code/jquery.citys.js

**Comment by shawndongyangyang** [comment]
@mumuy 第一，现在统计局数据源更新了，您的项目是否也可以更新，
第二，http://jquerywidget.com/jquery-citys/这个打不开了，
第三，http://passer-by.com/里面的很多项目也打不开了，
第四，我看你的哪个js源码，也没看懂省市区的算法规则，可否文字描述，万分感谢

**Comment by mumuy** [comment]
一共6位，按省、市、区三级划分，每两位一级

**Comment by shawndongyangyang** [comment]
现在的数据是什么时候的数据

**Comment by mumuy** [comment]
9月份呀
