### ISSUE TITLE
为什么我的town获取时，使用jsonp就报错，但省市区的list就没问题

### ISSUE THREAD

**Issue by katherine1191** [mumuy/data_location#30]
报错信息如下：
XMLHttpRequest：{readyState: 4, getResponseHeader: ƒ, getAllResponseHeaders: ƒ, setRequestHeader: ƒ, overrideMimeType: ƒ, …}
textStatus： parsererror
errorThrown：  Error: jsonp_location was not called

**Comment by mumuy** [comment]
之前文件出错了
