### ISSUE TITLE
"411622":"西华县", 据我所知身份证上西华县是 412722

### ISSUE THREAD

**Issue by erastudio** [mumuy/data_location#32]
"411622":"西华县", 据我所知身份证上西华县是 412722

是编码共用还是有有误？ 请指点，这些数据官网哪个网站可查？

**Comment by erastudio** [comment]
我在民政部查的也是 411622， 那是说以前用过412722来划分，但是现在不用了是吗？

原本打算使用身份证前6位判断会员所属区域的。 但这样的话，部分号段就判断不出来了

**Comment by mumuy** [comment]
是的，部分老的不再用，但是已经分配出去的身份证号码不会让你改
