### ISSUE TITLE
湖北省十堰市里面有个「武当山旅游经济特区」

### ISSUE THREAD

**Issue by xfanwu** [mumuy/data_location#33]
Wiki：[武当山旅游经济特区](https://zh.wikipedia.org/wiki/%E6%AD%A6%E5%BD%93%E5%B1%B1%E6%97%85%E6%B8%B8%E7%BB%8F%E6%B5%8E%E7%89%B9%E5%8C%BA)

**Comment by mumuy** [comment]
行政区和行政管理区的区别请认真搞清楚了！如果是行政区，挂牌的一定是xx区人民政府，而你所谓的武当山旅游经济特区，挂牌的是“武当山特区管理委员会”

**Comment by xfanwu** [comment]
懂了！是我没弄清楚，谢谢！
