### ISSUE TITLE
深圳没有大鹏和光明区？

### ISSUE THREAD

**Issue by royue** [mumuy/data_location#34]
深圳 大鹏新区和光明新区

**Comment by mumuy** [comment]
请注意行政区和行政管理区的差别，大鹏新区行政上属于龙岗区，光明新区行政上属于宝安区

**Comment by mumuy** [comment]
恭喜了，就在今年9月份，现在“光明新区”已经正式改为“光明区”了，由功能区变更为行政区，设立了人民政府
