### ISSUE TITLE
有没有整理成mysql版本的啊

### ISSUE THREAD

**Issue by eaglepie** [mumuy/data_location#35]
大神，有没有整理成mysql版本的啊，能提供一份么？

**Comment by mumuy** [comment]
没有

**Comment by z-jingjie** [comment]
网友2018年年初提供的，数据具体是哪一版本，暂不清楚
出处：https://www.v2ex.com/t/301610#r_5193958
网盘：https://pan.baidu.com/s/1kW18Md5
