### ISSUE TITLE
没有福州长乐县下级的乡镇数据文件

### ISSUE THREAD

**Issue by TerryZ** [mumuy/data_location#36]
福建-福州-长乐（350112）

长乐下级的乡/镇对应的文件缺少（350112.json）

**Comment by TerryZ** [comment]
发现实际上是有长乐县下级的乡镇数据（350182.json），但原来长乐是县（350182），现在行政编码变成了区（350112）

原来的乡镇数据就对不上了

另外甘肃省下的嘉峪关市（620200），根据统计局查看到的下级的数据是市辖区（620201），需要使用该区县代码才可以关联到乡镇数据（620201.json）

**Comment by mumuy** [comment]
文件已经补充上去了
