### ISSUE TITLE
selected初始化

### ISSUE THREAD

**Issue by nordon-wang** [mumuy/data_location#40]
当初始化之前选中的地区时，若是上海、北京城市，值是没有的，若是不给一个默认值会报警告
{province:'350000',city:'350100',area:'0',town:'0'}，要给一个默认值为0的才可以

**Comment by nordon-wang** [comment]
不是area为空，而是city为空

**Comment by lamplinx** [comment]
selected重新再次，多次赋值，有问题呢！！操作细节如下：
我是一个列表，点开编辑，数据是有存好的省市区。点第一个编辑框，省市区正常显示；关掉接着点列表第二条数据的编辑按钮，编辑界面的省市区显示不正常，只显示了省。接着点第三个又显示正常了。第四个不正常。。一次正常，一次不正常交替了···

**Comment by mumuy** [comment]
这个是插件的问题，并非当前数据库
