### ISSUE TITLE
第四级数据有些未取到

### ISSUE THREAD

**Issue by bromiao** [mumuy/data_location#41]
第四级数据有些未取到，如四川省德阳市罗江区下的镇/街道，四川省成都市郫都区下的镇/街道。。希望尽快修改数据库数据和json文件，很多开发者都在用。。。谢谢啦
![1531280633 1](https://user-images.githubusercontent.com/19767083/42549631-c0403312-84ff-11e8-8f87-0b9494ac3e2e.png)

**Comment by mumuy** [comment]
很多开发者？？？
