### ISSUE TITLE
有几个顺序不对

### ISSUE THREAD

**Issue by gbl2014** [mumuy/data_location#46]
"140311":"郊区",
"140321":"平定县",
"140322":"盂县",
"140400":"长治市",
"140402":"潞州区",
    "140421":"上党区",
    "140424":"屯留区",
    "140481":"潞城区",
"140423":"襄垣县",
"140425":"平顺县",
"140426":"黎城县",

**Comment by mumuy** [comment]
不对在哪里？？？

**Comment by mumuy** [comment]
撤县建区，暂时没分配到新的区划代码，一律按之前的来

**Comment by gbl2014** [comment]
我是说上面这几个的排序，没按 从小到大的顺序 排列
如：140424 后面是 140481，再后面却是140423

**Comment by mumuy** [comment]
没说是按顺序来的啊

**Comment by mumuy** [comment]
只是映射关系，没说按顺序来的呀，怎么会不对呢
