### ISSUE TITLE
密云区是110118000000，延庆区是110119000000	

### ISSUE THREAD

**Issue by hellozhangwei** [mumuy/data_location#49]

**Comment by mumuy** [comment]
区县及以上行政区划直接取的是前6位数，有什么问题吗？

**Comment by hellozhangwei** [comment]
我的意思密云和延庆的编码已经修改成我说的那个了。请参考http://www.stats.gov.cn/tjsj/tjbz/tjyqhdmhcxhfdm/2018/11/1101.html

**Comment by mumuy** [comment]
没有修改，在实际使用中可以忽略6位以后的，你可以参考
国家民政局：http://www.mca.gov.cn/article/sj/xzqh/2018/201804-12/20181201301111.html
国家标准化公示文件：http://www.gb688.cn/bzgk/gb/newGbInfo?hcno=C9C488FD717AFDCD52157F41C3302C6D
请认真阅读！

**Comment by hellozhangwei** [comment]
抱歉，我看错了。
