### ISSUE TITLE
张家口那里是不是有点不对？

### ISSUE THREAD

**Issue by qex** [mumuy/data_location#5]
> 《国务院关于同意河北省调整张家口市部分行政区划的批复》（国函〔2016〕5号）：
>
>一、同意撤销张家口市宣化区和宣化县，设立新的张家口市宣化区，以原宣化区和宣化县的行政区域（不含沙岭子镇、大仓盖镇、姚家房镇、东望山乡）为新的宣化区的行政区域，宣化区人民政府驻建国街街道永安街8号。
>
>二、同意撤销万全县，设立张家口市万全区，以原万全县的行政区域为万全区的行政区域，万全区人民政府驻孔家庄镇民主街2号。
>
>三、同意撤销崇礼县，设立张家口市崇礼区，以原崇礼县的行政区域为崇礼区的行政区域，崇礼区人民政府驻西湾子镇长青路30号。
>
>四、同意将原宣化县的大仓盖镇、东望山乡划归张家口市桥东区管辖，将原宣化县的沙岭子镇、姚家房镇划归张家口市桥西区管辖。

这是不是再也没有宣化县万全县和崇礼县的意思了？

**Comment by mumuy** [comment]
撤销了啊！撤销县改区了。。。我的数据没问题啊
