### ISSUE TITLE
台湾地区的code与国家民政局公布的code不一致

### ISSUE THREAD

**Issue by LuHugo** [mumuy/data_location#52]
国家民政局公布的台湾地区的 code是 710000
参考[《2019年7月中华人民共和国县以上行政区划代码》](http://www.mca.gov.cn/article/sj/xzqh/2019/201908/201908271607.html)

**Comment by mumuy** [comment]
我知道，但是现在台湾在大陆的居民居住证是以83开头的

**Comment by LuHugo** [comment]
@mumuy 居住证这个倒是没见过，尴尬了，小程序微信地址选择返回的也是710000……

**Comment by mumuy** [comment]
就是因为考虑到这个，在目前的居住证是这么安排的。到将来某一天真的统一了，那肯定会继续延用的。71是之前的行政区划代码
