### ISSUE TITLE
行政区已经改变了的，town文件夹中文件id对应区县district找不到

### ISSUE THREAD

**Issue by pipilove** [mumuy/data_location#55]
if district_id == 321071:  # 行政区已经改变了的
        district_id = 321003
    elif district_id == 511521:
        district_id = 511504
    elif district_id == 430372:  # todo
        district_id = 430304
    elif district_id == 542231:
        district_id = 540529
    elif district_id == 542227:
        district_id = 540526
    elif district_id == 542421:
        district_id = 540602  # 色尼区
    elif district_id == 469003:  # --那大镇
        district_id = 460400  # 儋州市
    elif district_id == 510124:
        district_id = 510117  # 郫都区
    elif district_id == 500228:
        district_id = 500155  # 梁平区
    elif district_id == 150171:
        district_id = 150171  # 梁平区
    elif district_id == 320772:
        district_id = 320706  # 海州区
    elif district_id == 211121:
        district_id = 211104  # 大洼区
    elif district_id == 500234:
        district_id = 500154  # 开州区
    elif district_id == 430124:
        district_id = 430182  # 宁乡市
    elif district_id == 360622:
        district_id = 360603  # 余江区
    elif district_id == 513229:
        district_id = 513201  # 马尔康市
    elif district_id == 130223:
        district_id = 130224  # 滦南县
    elif district_id == 139002:
        district_id = 130181  # 辛集市
    elif district_id == 361029:
        district_id = 361003  # 东乡区
    elif district_id == 130429:
        district_id = 130408  # 永年县
    elif district_id == 511028:
        district_id = 511083  # 隆昌市
    elif district_id == 360721:
        district_id = 360704  # 赣县区
    elif district_id == 522322:
        district_id = 522302  # 兴仁市
    elif district_id == 140203:
        district_id = 140214  # 云冈区
    elif district_id == 500232:
        district_id = 500156  # 武隆区
    elif district_id == 420821:
        district_id = 420882  # 京山市
    elif district_id == 130823:
        district_id = 130881  # 平泉市
    elif district_id == 411222:
        district_id = 411203  # 陕州区
    elif district_id == 542430:
        district_id = 540629  # 尼玛县
    elif district_id == 140424:
        district_id = 140405  # 屯留区
    elif district_id == 512081:
        district_id = 510185  # 简阳市
    elif district_id == 120225:
        district_id = 120119  # 蓟州区
    elif district_id == 330185:
        district_id = 330112  # 临安区
    elif district_id == 371626:
        district_id = 371681  # 邹平市
    elif district_id == 350182:
        district_id = 350112  # 长乐区
    elif district_id == 451281:
        district_id = 451203  # 宜州区
    elif district_id == 370282:
        district_id = 370215  # 即墨区
    elif district_id == 652201:
        district_id = 650502  # 伊州区
    elif district_id == 340823:
        district_id = 340722  # 枞阳县
    elif district_id == 510724:
        district_id = 510705  # 安州区
    elif district_id == 610823:
        district_id = 610803  # 横山区
    elif district_id == 510122:
        district_id = 510116  # 双流区
    elif district_id == 310230:
        district_id = 310151  # 崇明区
    elif district_id == 520222:
        district_id = 520281  # 盘州市
    elif district_id == 210282:
        district_id = 210214  # 普兰店区
    elif district_id == 210122:
        district_id = 210115  # 辽中区
    elif district_id == 610721:
        district_id = 610703  # 南郑区
    elif district_id == 370181:
        district_id = 370114  # 章丘区
    elif district_id == 140227:
        district_id = 140215  # 云州区
    elif district_id == 520321:
        district_id = 520304  # 播州区
    elif district_id == 139001:
        district_id = 130682  # 定州市
    elif district_id == 110229:
        district_id = 110119  # 延庆区
    elif district_id == 110228:
        district_id = 110118  # 密云区
    elif district_id == 360421:
        district_id = 360404  # 柴桑区
    elif district_id == 340824:
        district_id = 340882  # 潜山市
    elif district_id == 341521:
        district_id = 340422  # 寿县
    elif district_id == 610125:
        district_id = 610118  # 鄠邑区
    elif district_id == 130721:
        district_id = 130705  # 宣化区
    elif district_id == 371727:
        district_id = 371703  # 定陶区
    elif district_id == 371727:
        district_id = 140402  # 潞州区
    elif district_id == 610427:
        district_id = 610482  # 彬州市
    elif district_id == 340172:
        district_id = 340104  # 蜀山区
    elif district_id == 320871:
        district_id = 320803  # 淮安区
    elif district_id == 610821:
        district_id = 610881  # 神木市
    elif district_id == 450221:
        district_id = 450206  # 柳江区
    elif district_id == 371202:
        district_id = 370116  # 莱芜区
    elif district_id == 331021:
        district_id = 331083  # 玉环市
    elif district_id == 140202:
        district_id = 140213  # 平城区
    elif district_id == 620824:
        district_id = 620881  # 华亭市
    elif district_id == 652222:
        district_id = 650521  # 巴里坤哈萨克自治县
    elif district_id == 411023:
        district_id = 411003  # 建安区
    elif district_id == 450331:
        district_id = 450381  # 荔浦市

**Comment by mumuy** [comment]
在说明里面有写啊！town文件夹中文件是覆盖的。。。
