### ISSUE TITLE
能否导出一份sql文件

### ISSUE THREAD

**Issue by aacsok** [mumuy/data_location#57]
能否导出一份sql文件？别骂我伸手党 ^_^

**Comment by mumuy** [comment]
不提供，只提供json数据

**Comment by tjlizz** [comment]
[这里有](https://github.com/lizeze/china_region)  不过数据还没整理全，感谢大神整理这么完整的数据

**Comment by xiangyuecn** [comment]
欢迎使用我的一个类似的库： https://github.com/xiangyuecn/AreaCity-JsSpider-StatsGov 提供了转成sql文件、导入数据库支持，另外有坐标边界数据😊
