### ISSUE TITLE
区对应街道多文件问题

### ISSUE THREAD

**Issue by busyfree** [mumuy/data_location#63]
区代码 110118 , 110119 对应对街道文件夹code里面 110118.json, 110119.json。

那110228.json，110229.json 这2个文件是有什么用？备份？

![image](https://user-images.githubusercontent.com/504251/91678551-6fa66480-eb78-11ea-8ecb-87a1abdb8f02.png)
![image](https://user-images.githubusercontent.com/504251/91678599-89e04280-eb78-11ea-9cad-7d288a16c040.png)
![image](https://user-images.githubusercontent.com/504251/91678612-96649b00-eb78-11ea-89b0-070a92653901.png)

**Comment by mumuy** [comment]
有些编码被遗弃了，但是第四级的编码文件我是异步请求的，采用覆盖上传的，保证旧版本能找到对应的地址

**Comment by busyfree** [comment]
👌
