### ISSUE TITLE
441900.json 442000.json 里面的城镇是位数比其他的多

### ISSUE THREAD

**Issue by phpseven** [mumuy/data_location#68]
其他的都是 9位 （ 如"441882101":"连州镇"）， 但是这2个 json里面是12位
442000.json
441900.json

{"441900003000":"东城街道办事处","441900004000":"南城街道办事处","441900005000":"万江街道办事处","441900006000":"莞城街道办事处","441900101000":"石碣镇","441900102000":"石龙镇","441900103000":"茶山镇","441900104000":"石排镇","441900105000":"企石镇","441900106000":"横沥镇","441900107000":"桥头镇","441900108000":"谢岗镇","441900109000":"东坑镇","441900110000":"常平镇","441900111000":"寮步镇","441900112000":"樟木头镇","441900113000":"大朗镇","441900114000":"黄江镇","441900115000":"清溪镇","441900116000":"塘厦镇","441900117000":"凤岗镇","441900118000":"大岭山镇","441900119000":"长安镇","441900121000":"虎门镇","441900122000":"厚街镇","441900123000":"沙田镇","441900124000":"道滘镇","441900125000":"洪梅镇","441900126000":"麻涌镇","441900127000":"望牛墩镇","441900128000":"中堂镇","441900129000":"高埗镇","441900401000":"松山湖管委会","441900402000":"虎门港管委会","441900403000":"东莞生态园"}

**Comment by mumuy** [comment]
已解决
