### ISSUE TITLE
兰州市兰州新区的行政区划代码缺失，以及下属街道，望更新

### ISSUE THREAD

**Issue by oujinnian** [mumuy/data_location#75]
![image](https://github.com/user-attachments/assets/a278d846-500c-4554-abe8-6adf00e05650)

**Comment by mumuy** [comment]
兰州新区并不非民政部规定的“行政区”而是属于“行政管理区”，没有正式的行政区建制，属于国家级新区，由区管理委员会管理，而非区人民政府。你看的属于是国家统计局为了方便，加入了一部分“行政管理区”的代码，这些代码非标准的行政区划代码。
由于我的第四级数据来自于统计局，是有所属的街道数据的，但行政上并非直接隶属

**Comment by mumuy** [comment]
也就是说：秦川镇、中川镇、西岔镇、上川镇四镇行政上属于皋兰县，交由兰州新区托管。

**Comment by mumuy** [comment]
如果你想包含“行政管理区”数据，可改使用 https://passer-by.com/data_location/list2.json  这个数据
