### ISSUE TITLE
自个把这些导入到数据库，然后自个写个编辑数据的小程序

### ISSUE THREAD

**Issue by nottellyou** [mumuy/data_location#8]
自个把这些导入到数据库，然后自个写个编辑数据的小程序，导入一次，以后慢慢更新，就方便多了。

不知道你是不是数据库存储的

**Comment by mumuy** [comment]
我的数据都是放在json文件上的，是行政区划代码和行政区名称的键值对关系

**Comment by nottellyou** [comment]
那如果要修改岂不是很不方便？

**Comment by mumuy** [comment]
不会啊，改数据库也是改，改文件也是改……本身就是键值对关系，没有复杂的嵌套。要改哪个编辑器搜索哪个

**Comment by nottellyou** [comment]
好吧，也辛苦你弄了这么多的数据，回头有时间，我看看能不能整到数据库里。毕竟远程调用延时有点高
